# Generated by Django 5.2 on 2026-05-15 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='update_count',
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='claimed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
