# Generated by Django 5.2 on 2026-05-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
